command: ["uvicorn", "app:app"]

env:
  - name: 'DATABRICKS_WAREHOUSE_ID'
    valueFrom: 'sql_warehouse'

  # Optional Databricks connection settings used by the SQL connector
  - name: 'DATABRICKS_HOST'
    value: ''
  - name: 'DATABRICKS_TOKEN'
    value: ''

  # Application settings for optional DB-backed features
  - name: 'LAKEBASE_INSTANCE_NAME'
    value: ''
  - name: 'LAKEBASE_DATABASE_NAME'
    value: ''
  - name: 'DATABRICKS_DATABASE_PORT'
    value: '5432'

  - name: 'DB_POOL_SIZE'
    value: '5'
  - name: 'DB_MAX_OVERFLOW'
    value: '10'
  - name: 'DB_COMMAND_TIMEOUT'
    value: '30'
  - name: 'DB_POOL_TIMEOUT'
    value: '10'
  - name: 'DB_POOL_RECYCLE_INTERVAL'
    value: '3600'