command: ["uvicorn", "app:app"]

env:
  - name: 'DATABRICKS_WAREHOUSE_ID'
    valueFrom: 'sql_warehouse'

  # Optional Databricks connection settings used by the SQL connector
  - name: 'DATABRICKS_HOST'
    value: ''
  - name: 'DATABRICKS_TOKEN'
    value: ''